doctores/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # path('', views.index),
    path('doctores', views.doctores),
    path("doctores/update/<int:id_doctor>", views.actualizar_doctor),
    path("doctores/delete/<int:id_doctor>", views.eliminar_doctor)
    
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('autenticacion.urls')),
    #
    path("", include('doctores.urls')),
    path("", include('especialidades.urls')),
    path("", include('consultorios.urls')),
    path("", include('pacientes.urls')),
    path("", include('reservas.urls')),

]

consultorios/models.py
from django.db import models

from especialidades.models import Especialidad
from doctores.models import Doctor
# Create your models here.


class Consultorio(models.Model):
    nombre = models.CharField(max_length=20, unique=True)
    especialidad = models.ForeignKey(Especialidad, on_delete=models.CASCADE, blank=True, null=True)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, blank=True, null=True)
    
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"<{self.nombre} - {self.especialidad.nombre}> - {self.doctor.nombre}"
    
    class Meta:
        db_table = "Consultorio"


class Horario(models.Model):
    inicio = models.TimeField()
    fin = models.TimeField()
    turno = models.CharField(max_length=20)
    consultorio = models.ForeignKey(Consultorio, on_delete=models.CASCADE)


    def __str__(self):
        return f"<{self.consultorio.nombre} {self.inicio}  {self.fin}>"
    
    class Meta:
        db_table = "Horario"


class Equipo(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=255)

    consultorio = models.ForeignKey(Consultorio, on_delete=models.CASCADE)



    def __str__(self):
        return f"<{self.consultorio.nombre} {self.nombre} >"
    
    class Meta:
        db_table = "Equipo"

templates/reconsultas/pdf_template_reconsulta_comprobante.html
<head>
    <style>
        @page {
            size: a4 portrait;
            @frame header_frame {           /* Static Frame */
                -pdf-frame-content: header_content;
                left: 50pt; width: 512pt; top: 50pt; height: 40pt;
            }
            @frame content_frame {          /* Content Frame */
                left: 50pt; width: 512pt; top: 90pt; height: 632pt;
            }
            @frame footer_frame {           /* Another static Frame */
                -pdf-frame-content: footer_content;
                left: 50pt; width: 512pt; top: 772pt; height: 20pt;
            }
        }
    </style>
    </head>
    
    <body>
        <!-- Content for Static Frame 'header_frame' -->
        <div id="header_content">
            <h3>Clinica Divino Niño</h3>
            <h3>NIT: 48517760XX</h3>
            <h3>Comprobante de reserva de consulta</h3>
        </div>
    
        <!-- Content for Static Frame 'footer_frame' -->
        <div id="footer_content">(c) - page <pdf:pagenumber>
            of <pdf:pagecount>
        </div>
    
        <!-- HTML Content -->
        <table>
                <tr>
                    <td>Direccion: {{address}}</td>
                    <td>{{phone}}</td>
                </tr>
                <tr>
                    <td>Ciudad: {{city}},</td>
                </tr>
                <tr>
                    <td>Correo Electronico: {{website}}</td>
                </tr>
        </table>


        

        <div>
            <h3>INFORMACION DEL PACIENTE</h3>
        </div>

        <table>
                <tr>
                    <td>Nombre paciente: {{paciente.nombre}} {{paciente.apellido}}</td>
                </tr>
                <tr>
                    <td>Carnet de identidad: {{paciente.ci}}</td>
                </tr>

                <tr>
                    <td>telefono: {{paciente.telefono}}</td>
                </tr>
                <tr>
                    <td>Direccion: {{paciente.domicilio}}</td>
                </tr>
        </table>



        
    

        <div>
            <h3>INFORMACION DE LA RECONSULTA</h3>
        </div>

        <hr>
    
        <table>
            <tr>
                <th scope="col">Consultorio</th>
                <th scope="col">Paciente</th>
                <th scope="col">Doctor</th>
                <th scope="col">Especialidad</th>
                <th scope="col">Fecha</th>
                <th scope="col">Hora Inicio</th>
                <th scope="col">Hora Fin</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                  <td>{{reserva.consultorio.nombre}}</td>
                  <td>{{reserva.paciente.nombre}} {{reserva.paciente.apellido}}</td>
                  <td>{{reserva.consultorio.doctor.nombre}} {{reserva.consultorio.doctor.apellido}}</td>
                  <td>{{reserva.consultorio.especialidad.nombre}}</td>
                  <td>{{reserva.fecha_reserva}}</td>
                  <td>{{reserva.inicio}}</td>
                  <td>{{reserva.fin}}</td>

                </tr>
            </tbody>
            
        </table>
    
        <hr>
        <p><strong>Precio de la consulta: LA RECONSULTA NO TIENE COSTO ALGUNO :)</strong></p>
    </body>
    </html>

templates/reconsultas/reconsultas.html
{% extends 'layouts/base.html' %}

{% block customCSS %}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>

{% endblock %}

{% block content %}
<h1>Reconsultas</h1>
<div class="row">
  <div class="col-md-5">
    <form action="/reconsultas" method="post">
      {% csrf_token %}

      <div class="form-group">
        <label for="sueldo">Seleccione el paciente</label>
        <select name="paciente_id" class="form-select"  aria-label="Default select example">
          {% for paciente in pacientes %}
            <option value="{{paciente.id}}">{{paciente.nombre}} {{paciente.apellido}}</option>
          {% endfor %}
        </select>
      </div>


      <div class="form-group">
        <label for="sueldo">Seleccione el Consultorio</label>
        <select name="consultorio_horario" class="form-select"  aria-label="Default select example">
          {% for consultorio in consultorios %}
            {% for horario in consultorio.horario_set.all %}
            <option value="{{consultorio.id}} {{horario.id}}">{{consultorio}} {{horario}}</option>
            {% endfor %}
          {% endfor %}
        </select>
      </div>

    
      <label for="nombre">Fecha de la consulta</label>
      <br>
      <div class="input-group date" id="datepicker">
        
        <input name="fecha_reserva" type="text" class="form-control" placeholder="seleccione la fecha" required>
        <span class="input-group-append">
            <span class="input-group-text bg-white d-block">
                <i class="fa fa-calendar"></i>
            </span>
        </span>
      </div>

    


      <button type="submit">Registrar Reconsulta</button>
    </form>
  </div>
  <div class="col-md-7">
    {% if reservas|length > 0 %}
        <table class="table">
            <thead>
              <tr>
                <th scope="col">Id</th>
                <th scope="col">Consultorio</th>
                <th scope="col">Paciente</th>
                <th scope="col">Doctor</th>
                <th scope="col">Especialidad</th>
                <th scope="col">Fecha</th>
                <th scope="col">Hora Inicio</th>
                <th scope="col">Hora Fin</th>
                <th scope="col">Precio</th>
                <th scope="col">Comprobante</th>


              </tr>
            </thead>
            <tbody>
              {% for reserva in reservas %}
              <tr>
                  <th scope="row">{{reserva.id}}</th>
                  <td>{{reserva.consultorio.nombre}}</td>
                  <td>{{reserva.paciente.nombre}} {{reserva.paciente.apellido}}</td>
                  <td>{{reserva.consultorio.doctor.nombre}} {{reserva.consultorio.doctor.apellido}}</td>
                  <td>{{reserva.consultorio.especialidad.nombre}}</td>
                  <td>{{reserva.fecha_reserva}}</td>
                  <td>{{reserva.inicio}}</td>
                  <td>{{reserva.fin}}</td>
                  <td>RECONSULTA</td>

                  <td>
                    <a href="reconsulta/comprobante/{{reserva.id}}" class="btn btn-success">Comprobante Reconsulta</a>
                  </td>

                </tr>
              {% endfor %}
            </tbody>
          </table>
    {% else%}
        <h1>No hay Reconsultas Registradas!</h1>
    {% endif %}
    
  </div>
</div>
{% endblock %}

{% block customJavascript %} 

<script type="text/javascript">
    $(function() {
        $('#datepicker').datepicker();
    });
</script>

{% endblock %}